import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import Link from "next/link"

type ManifestEntry = {
  schema: "stack/artifact-page/v1"
  slug: string
  title: string
  kind: string
  effort?: string
  updated_at: string
  local_url: string
}

export default function ArtifactGalleryPage() {
  const artifacts = readArtifacts()
  return (
    <main className="artifact-shell">
      <section className="artifact-container">
        <h1>Artifact Site</h1>
        <p className="artifact-muted">Local artifact pages generated by Stack agents.</p>
        <div className="artifact-gallery">
          {artifacts.length === 0 ? (
            <p className="artifact-muted">No artifact pages yet.</p>
          ) : (
            artifacts.map((artifact) => (
              <Link key={artifact.slug} href={`/a/${artifact.slug}`} className="artifact-card">
                <span className="artifact-kind">{artifact.kind}</span>
                <strong>{artifact.title}</strong>
                <span className="artifact-muted">
                  {artifact.effort ? `effort ${artifact.effort} - ` : ""}
                  updated {artifact.updated_at}
                </span>
              </Link>
            ))
          )}
        </div>
      </section>
    </main>
  )
}

function readArtifacts(): ManifestEntry[] {
  const path = join(process.cwd(), "..", "manifest.jsonl")
  if (!existsSync(path)) return []
  const bySlug = new Map<string, ManifestEntry>()
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed) continue
    try {
      const entry = JSON.parse(trimmed) as ManifestEntry
      if (entry.schema === "stack/artifact-page/v1" && entry.slug) bySlug.set(entry.slug, entry)
    } catch {
      continue
    }
  }
  return [...bySlug.values()].sort((left, right) => right.updated_at.localeCompare(left.updated_at))
}
