#!/usr/bin/env bun

import { createHash } from "node:crypto"
import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { readVersionFile } from "../src/version-file.ts"

const stackRoot = join(import.meta.dir, "..")
const packagingDir = join(stackRoot, "packaging", "homebrew")
const repo = "synth-laboratories/stack"

type Args = {
  stableVersion?: string
  fetchStable: boolean
}

function parseArgs(argv: string[]): Args {
  const stableFlag = argv.find((arg) => arg.startsWith("--stable-version="))
  return {
    stableVersion: stableFlag?.split("=", 2)[1],
    fetchStable: argv.includes("--fetch-stable"),
  }
}

async function sha256ForUrl(url: string): Promise<string> {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`fetch failed ${response.status} ${url}`)
  const bytes = new Uint8Array(await response.arrayBuffer())
  return createHash("sha256").update(bytes).digest("hex")
}

function renderStableFormula(version: string, sha256: string): string {
  return `# GENERATED by scripts/update_homebrew_formula.ts — edit version.json then regenerate
class Stack < Formula
  desc "Synth operator cockpit — OpenTUI, Codex, and Stack MCP"
  homepage "https://github.com/${repo}"
  url "https://github.com/${repo}/archive/refs/tags/v${version}.tar.gz"
  version "${version}"
  sha256 "${sha256}"
  license "MIT"
  head do
    url "https://github.com/${repo}.git", branch: "main"
  end

  depends_on "bun"

  def install
    system "make", "install-brew", "PREFIX=#{prefix}", "LIBEXEC=#{libexec}/stack"
  end

  def caveats
    <<~EOS
      Stable channel. For daily dev builds: brew install synth-laboratories/tap/stack-dev
      Requires Codex CLI and Synth workspace config — see stack-local-setup skill.
    EOS
  end

  test do
    assert_match "${version}", shell_output("#{bin}/stack --version")
    assert_match "channel: stable", shell_output("#{bin}/stack --version")
  end
end
`
}

function renderDevFormula(): string {
  return `# GENERATED by scripts/update_homebrew_formula.ts
class StackDev < Formula
  desc "Synth operator cockpit (dev/nightly channel from main)"
  homepage "https://github.com/${repo}"
  license "MIT"

  head "https://github.com/${repo}.git", branch: "main"

  depends_on "bun"

  def install
    system "make", "install-brew", "PREFIX=#{prefix}", "LIBEXEC=#{libexec}/stack"
  end

  def caveats
    <<~EOS
      Dev/nightly channel — tracks main. Updates frequently via brew upgrade stack-dev.
      Public stable: brew install synth-laboratories/tap/stack
    EOS
  end

  test do
    assert_match "channel: dev", shell_output("#{bin}/stack --version")
  end
end
`
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2))
  const meta = readVersionFile(stackRoot)
  const stableVersion = args.stableVersion ?? meta.release
  let sha256 = "REPLACE_AFTER_TAG"

  if (args.fetchStable) {
    const url = `https://github.com/${repo}/archive/refs/tags/v${stableVersion}.tar.gz`
    sha256 = await sha256ForUrl(url)
    console.log(`fetched sha256 for v${stableVersion}`)
  }

  writeFileSync(join(packagingDir, "stack.rb"), renderStableFormula(stableVersion, sha256), "utf8")
  writeFileSync(join(packagingDir, "stack-dev.rb"), renderDevFormula(), "utf8")
  console.log(`homebrew formulas updated · stable v${stableVersion}`)
}

await main()
