# GENERATED by scripts/update_homebrew_formula.ts — edit version.json then regenerate
class Stack < Formula
  desc "Synth operator cockpit — OpenTUI, Codex, and Stack MCP"
  homepage "https://github.com/synth-laboratories/stack"
  url "https://github.com/synth-laboratories/stack/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "REPLACE_AFTER_TAG"
  license "LicenseRef-Synth-Proprietary"

  depends_on "bun"

  def install
    system "make", "install-brew", "PREFIX=#{prefix}", "LIBEXEC=#{libexec}/stack"
  end

  def caveats
    <<~EOS
      Stable channel (public release). Dev/nightly: brew install synth-laboratories/tap/stack-dev
      Requires Codex CLI and Synth workspace config — see stack-local-setup skill.
    EOS
  end

  test do
    assert_match "0.1.0", shell_output("#{bin}/stack --version")
    assert_match "channel: stable", shell_output("#{bin}/stack --version")
  end
end
