# GENERATED by scripts/update_homebrew_formula.ts
class StackDev < Formula
  desc "Synth operator cockpit (dev/nightly channel from main)"
  homepage "https://github.com/synth-laboratories/stack"
  license "LicenseRef-Synth-Proprietary"

  head "https://github.com/synth-laboratories/stack.git", branch: "main"

  depends_on "bun"

  def install
    system "make", "install-brew", "PREFIX=#{prefix}", "LIBEXEC=#{libexec}/stack"
  end

  def caveats
    <<~EOS
      Dev/nightly channel — tracks main. Update often: brew upgrade stack-dev
      Public stable: brew install synth-laboratories/tap/stack
    EOS
  end

  test do
    assert_match "channel: dev", shell_output("#{bin}/stack --version")
  end
end
